<?php

namespace Database\Seeders;

use App\Models\Expense;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ExpenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        Expense::insert([
            [
                'user_id' => 1,
                'category_id' => 5,
                'amount' => 5500,
                'content' => '電気代',
                'memo' => 'test',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'amount' => 15500,
                'content' => 'ガス代',
                'memo' => 'test',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 2,
                'category_id' => 4,
                'amount' => 10000,
                'content' => 'サブスク',
                'memo' => 'test',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'category_id' => 6,
                'amount' => 6000,
                'content' => '外食',
                'memo' => 'test',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'category_id' => 7,
                'amount' => 16000,
                'content' => '飲み会',
                'memo' => 'test',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'category_id' => 8,
                'amount' => 28000,
                'content' => '土地',
                'memo' => 'test',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'category_id' => 9,
                'amount' => 50000,
                'content' => '言えない',
                'memo' => 'test',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'amount' => 5500,
                'content' => '電気代',
                'memo' => 'test',
                'created_at' => $now->addMonth(),
                'updated_at' => $now->addMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'amount' => 15500,
                'content' => 'ガス代',
                'memo' => 'test',
                'created_at' => $now->addMonth(),
                'updated_at' => $now->addMonth(),
            ],
            [
                'user_id' => 2,
                'category_id' => 4,
                'amount' => 10000,
                'content' => 'サブスク',
                'memo' => 'test',
                'created_at' => $now->addMonth(),
                'updated_at' => $now->addMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 6,
                'amount' => 6000,
                'content' => '外食',
                'memo' => 'test',
                'created_at' => $now->addMonth(),
                'updated_at' => $now->addMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 7,
                'amount' => 16000,
                'content' => '飲み会',
                'memo' => 'test',
                'created_at' => $now->addMonth(),
                'updated_at' => $now->addMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 8,
                'amount' => 28000,
                'content' => '土地',
                'memo' => 'test',
                'created_at' => $now->addMonth(),
                'updated_at' => $now->addMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 9,
                'amount' => 50000,
                'content' => '言えない',
                'memo' => 'test',
                'created_at' => $now->addMonth(),
                'updated_at' => $now->addMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'amount' => 5500,
                'content' => '電気代',
                'memo' => 'test',
                'created_at' => $now->addMonth(2),
                'updated_at' => $now->addMonth(2),
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'amount' => 15500,
                'content' => 'ガス代',
                'memo' => 'test',
                'created_at' => $now->addMonth(2),
                'updated_at' => $now->addMonth(2),
            ],
            [
                'user_id' => 2,
                'category_id' => 4,
                'amount' => 10000,
                'content' => 'サブスク',
                'memo' => 'test',
                'created_at' => $now->addMonth(2),
                'updated_at' => $now->addMonth(2),
            ],
            [
                'user_id' => 1,
                'category_id' => 6,
                'amount' => 6000,
                'content' => '外食',
                'memo' => 'test',
                'created_at' => $now->addMonth(2),
                'updated_at' => $now->addMonth(2),
            ],
            [
                'user_id' => 1,
                'category_id' => 7,
                'amount' => 16000,
                'content' => '飲み会',
                'memo' => 'test',
                'created_at' => $now->addMonth(2),
                'updated_at' => $now->addMonth(2),
            ],
            [
                'user_id' => 1,
                'category_id' => 8,
                'amount' => 28000,
                'content' => '土地',
                'memo' => 'test',
                'created_at' => $now->addMonth(2),
                'updated_at' => $now->addMonth(2),
            ],
            [
                'user_id' => 1,
                'category_id' => 9,
                'amount' => 50000,
                'content' => '言えない',
                'memo' => 'test',
                'created_at' => $now->addMonth(2),
                'updated_at' => $now->addMonth(2),
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'amount' => 5500,
                'content' => '電気代',
                'memo' => 'test',
                'created_at' => $now->subMouth(),
                'updated_at' => $now->subMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 5,
                'amount' => 15500,
                'content' => 'ガス代',
                'memo' => 'test',
                'created_at' => $now->subMouth(),
                'updated_at' => $now->subMonth(),
            ],
            [
                'user_id' => 2,
                'category_id' => 4,
                'amount' => 10000,
                'content' => 'サブスク',
                'memo' => 'test',
                'created_at' => $now->subMouth(),
                'updated_at' => $now->subMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 6,
                'amount' => 6000,
                'content' => '外食',
                'memo' => 'test',
                'created_at' => $now->subMouth(),
                'updated_at' => $now->subMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 7,
                'amount' => 16000,
                'content' => '飲み会',
                'memo' => 'test',
                'created_at' => $now->subMouth(),
                'updated_at' => $now->subMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 8,
                'amount' => 28000,
                'content' => '土地',
                'memo' => 'test',
                'created_at' => $now->subMouth(),
                'updated_at' => $now->subMonth(),
            ],
            [
                'user_id' => 1,
                'category_id' => 9,
                'amount' => 50000,
                'content' => '言えない',
                'memo' => 'test',
                'created_at' => $now->subMouth(),
                'updated_at' => $now->subMonth(),
            ],

        ]);
    }
}
